FROM ubuntu:22.04
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y sudo python3
RUN useradd -m mattie -G sudo -s /bin/bash
RUN echo 'mattie:8bitguy' | chpasswd
ARG path
RUN mkdir -p $path
RUN chown mattie $path